language: python
script: ls
deploy:
  matrix:
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: SteinHeselmans
    password:
        secure: mGz3ih+7sFLiijlXvzRaN1pvCLHQxpx0TCS74vbytBjDNn+w0xNl/FR+ahffXOnETf2LutzJE+c74XsGSuw2QcQhtqI9+R+zc76UazArbE34bvVsxd5jp5DYFcw3k+FKnm/dHFNSGbx2oJB5rNN3S6D0X/s5+u4vo8HYsl7LW2Nbr3BzIDB8TLrJW42zxomDHT90RqaOdOjN7nDWB1PLW7UFmuAHmAwFA4CQLKaYY9acBd1xiBb16o4EbroLcbd3kZE+n3XjxafUqkTbPU7PFxNDuP3ddQrrgDYQQ0uts4JLKZtaVaRVhZvRJi9632N031523u8XBTF1+KK8LfSCeY0h1TsvdKuM48UPSaV1ev08cX4gYD4OMXgSUvk3MuUIZ+FKIkshbqENGlTfQcIxMgLLDtgrjJQ8qXVrCk28Bk22+hdMIHX+Ox2bkfaDzJx6fU0S85gYSC+veEYDeKy8Z1+8jja2ticvQcfqByGe6hWasin6qhtjZ27LNBmEJx4jdaXlxDsjmlYyAmjU1Dflyx9JlFA4w36nZJpQvtBN9LvjipO7cJ1Uzuy57DynmdtreZAorTQaCX4NkbvLkS6K4bsK1m48eiAxVPhquagtdI9S9dmvJFTCtULAdA7eLZI3zxmVKGwxbG7VStW70n+vb/UEjdUDAQVW84iOgRMrIp8=
    on:
      branch: master
      tags: false
  - provider: pypi
    distributions: sdist
    user: SteinHeselmans
    password:
        secure: mGz3ih+7sFLiijlXvzRaN1pvCLHQxpx0TCS74vbytBjDNn+w0xNl/FR+ahffXOnETf2LutzJE+c74XsGSuw2QcQhtqI9+R+zc76UazArbE34bvVsxd5jp5DYFcw3k+FKnm/dHFNSGbx2oJB5rNN3S6D0X/s5+u4vo8HYsl7LW2Nbr3BzIDB8TLrJW42zxomDHT90RqaOdOjN7nDWB1PLW7UFmuAHmAwFA4CQLKaYY9acBd1xiBb16o4EbroLcbd3kZE+n3XjxafUqkTbPU7PFxNDuP3ddQrrgDYQQ0uts4JLKZtaVaRVhZvRJi9632N031523u8XBTF1+KK8LfSCeY0h1TsvdKuM48UPSaV1ev08cX4gYD4OMXgSUvk3MuUIZ+FKIkshbqENGlTfQcIxMgLLDtgrjJQ8qXVrCk28Bk22+hdMIHX+Ox2bkfaDzJx6fU0S85gYSC+veEYDeKy8Z1+8jja2ticvQcfqByGe6hWasin6qhtjZ27LNBmEJx4jdaXlxDsjmlYyAmjU1Dflyx9JlFA4w36nZJpQvtBN9LvjipO7cJ1Uzuy57DynmdtreZAorTQaCX4NkbvLkS6K4bsK1m48eiAxVPhquagtdI9S9dmvJFTCtULAdA7eLZI3zxmVKGwxbG7VStW70n+vb/UEjdUDAQVW84iOgRMrIp8=
    on:
      branch: master
      tags: true
